# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/thatslc/PycharmProjects/ImageFace/ui_files/showUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_showUI(object):
    def setupUi(self, showUI):
        showUI.setObjectName("showUI")
        showUI.setWindowModality(QtCore.Qt.WindowModal)
        showUI.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(showUI.sizePolicy().hasHeightForWidth())
        showUI.setSizePolicy(sizePolicy)
        showUI.setMinimumSize(QtCore.QSize(1000, 700))
        showUI.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(showUI)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 171, 681))
        self.listWidget.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid #dfdfdf;\n"
"background-color: rgba(0,0,0,0);")
        self.listWidget.setObjectName("listWidget")
        self.bird = QtWidgets.QLabel(self.centralwidget)
        self.bird.setGeometry(QtCore.QRect(210, 10, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bird.setFont(font)
        self.bird.setObjectName("bird")
        self.rightNUM = QtWidgets.QLabel(self.centralwidget)
        self.rightNUM.setGeometry(QtCore.QRect(740, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(40)
        font.setStrikeOut(False)
        self.rightNUM.setFont(font)
        self.rightNUM.setText("")
        self.rightNUM.setAlignment(QtCore.Qt.AlignCenter)
        self.rightNUM.setObjectName("rightNUM")
        self.wrongNUM = QtWidgets.QLabel(self.centralwidget)
        self.wrongNUM.setGeometry(QtCore.QRect(870, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(40)
        font.setStrikeOut(False)
        self.wrongNUM.setFont(font)
        self.wrongNUM.setText("")
        self.wrongNUM.setAlignment(QtCore.Qt.AlignCenter)
        self.wrongNUM.setObjectName("wrongNUM")
        self.mAP1 = QtWidgets.QLabel(self.centralwidget)
        self.mAP1.setGeometry(QtCore.QRect(210, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP1.setFont(font)
        self.mAP1.setText("")
        self.mAP1.setObjectName("mAP1")
        self.mAP2 = QtWidgets.QLabel(self.centralwidget)
        self.mAP2.setGeometry(QtCore.QRect(310, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP2.setFont(font)
        self.mAP2.setText("")
        self.mAP2.setObjectName("mAP2")
        self.mAP3 = QtWidgets.QLabel(self.centralwidget)
        self.mAP3.setGeometry(QtCore.QRect(410, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP3.setFont(font)
        self.mAP3.setText("")
        self.mAP3.setObjectName("mAP3")
        self.mAP4 = QtWidgets.QLabel(self.centralwidget)
        self.mAP4.setGeometry(QtCore.QRect(510, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP4.setFont(font)
        self.mAP4.setText("")
        self.mAP4.setObjectName("mAP4")
        self.mAP2_2 = QtWidgets.QLabel(self.centralwidget)
        self.mAP2_2.setGeometry(QtCore.QRect(310, 60, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP2_2.setFont(font)
        self.mAP2_2.setObjectName("mAP2_2")
        self.mAP1_2 = QtWidgets.QLabel(self.centralwidget)
        self.mAP1_2.setGeometry(QtCore.QRect(210, 60, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP1_2.setFont(font)
        self.mAP1_2.setObjectName("mAP1_2")
        self.mAP3_2 = QtWidgets.QLabel(self.centralwidget)
        self.mAP3_2.setGeometry(QtCore.QRect(410, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP3_2.setFont(font)
        self.mAP3_2.setObjectName("mAP3_2")
        self.mAP4_2 = QtWidgets.QLabel(self.centralwidget)
        self.mAP4_2.setGeometry(QtCore.QRect(510, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mAP4_2.setFont(font)
        self.mAP4_2.setObjectName("mAP4_2")
        showUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(showUI)
        QtCore.QMetaObject.connectSlotsByName(showUI)

    def retranslateUi(self, showUI):
        _translate = QtCore.QCoreApplication.translate
        showUI.setWindowTitle(_translate("showUI", "FourSearch"))
        self.bird.setText(_translate("showUI", "Bird"))
        self.mAP2_2.setText(_translate("showUI", "mAP N=5"))
        self.mAP1_2.setText(_translate("showUI", "mAP N=1"))
        self.mAP3_2.setText(_translate("showUI", "mAP N=10"))
        self.mAP4_2.setText(_translate("showUI", "mAP N=50"))

